# Generated by Django 6.0.2 on 2026-02-19 03:43

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture (max 2MB)', null=True, upload_to=apps.accounts.models.profile_picture_path, validators=[apps.accounts.models.validate_image_size]),
        ),
    ]
