# Generated by Django 6.0.2 on 2026-03-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('doctor', 'Doctor')], default='user', help_text='User role for access control', max_length=10),
        ),
    ]
