# Generated by Django 6.0.2 on 2026-02-11 15:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the service', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the service')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Duration of the service in minutes')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the service', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('image', models.ImageField(blank=True, help_text='Service image', null=True, upload_to='services/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
    ]
