# Generated by Django 6.0.2 on 2026-02-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('diagnostic', 'Diagnostic & Testing'), ('dental', 'Dental Care'), ('therapy', 'Therapy & Rehabilitation'), ('mental_health', 'Mental Health'), ('specialist', 'Specialist Consultation'), ('wellness', 'Wellness & Nutrition'), ('emergency', 'Emergency Services'), ('other', 'Other Services')], default='other', help_text='Service category', max_length=50),
        ),
    ]
