# Generated by Django 6.0.2 on 2026-02-19 03:43

import apps.services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Service image (max 5MB, JPG/PNG/WEBP)', null=True, upload_to=apps.services.models.service_image_path, validators=[apps.services.models.validate_image_size]),
        ),
    ]
