# Generated by Django 6.0.2 on 2026-03-09 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_doctor_education_experience_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.doctor'),
        ),
    ]
