# Generated by Django 6.0.2 on 2026-03-24 14:46

import apps.services.models
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_doctor_bio_doctor_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('diagnostic', 'Diagnostic & Testing'), ('dental', 'Dental Care'), ('therapy', 'Therapy & Rehabilitation'), ('mental_health', 'Mental Health'), ('specialist', 'Specialist Consultation'), ('wellness', 'Wellness & Nutrition'), ('emergency', 'Emergency Services'), ('other', 'Other Services')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Detailed description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.services.models.service_image_path, validators=[apps.services.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
