# Generated by Django 6.0.2 on 2026-04-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_service_options_alter_service_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('general_medicine', 'General Medicine'), ('cardiovascular_health', 'Cardiovascular Health'), ('skin_aesthetics', 'Skin & Aesthetics'), ('musculoskeletal_care', 'Musculoskeletal Care'), ('child_health', 'Child Health'), ('womens_health', "Women's Health"), ('brain_nerve_care', 'Brain & Nerve Care'), ('mental_health', 'Mental Health'), ('oral_health', 'Oral Health'), ('ear_nose_throat', 'Ear, Nose, & Throat'), ('urinary_renal_care', 'Urinary & Renal Care'), ('respiratory_medicine', 'Respiratory Medicine'), ('wellness', 'Wellness & Nutrition'), ('emergency', 'Emergency Services'), ('other', 'Other Services')], default='other', max_length=50),
        ),
    ]
