# Generated by Django 6.0.2 on 2026-04-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
